In [78]:
import numpy as np
a=np.array([2.0,3.0])
b= np.array([[2,4], [5,6], [3,7]])
a, b

(array([2., 3.]),
 array([[2, 4],
        [5, 6],
        [3, 7]]))

In [79]:
print(a)

[2. 3.]


In [80]:
#get dimension
a.ndim

1

In [81]:
#get shape
a.shape
b.shape #3 rows, 2 columns

(3, 2)

In [82]:
#get data type(bits)
a.dtype

dtype('float64')

In [83]:
#get byte size of each element
a.itemsize

8

In [84]:
b.itemsize

4

In [85]:
a.nbytes #=total size of a= a.itemsize * no of elements

16

In [86]:
a[0]

2.0

In [89]:
b[2,0], b[1,0], b[0,1],b[-1,-1],b[-2,-2] # -2,-2 shows [2nd last row,2nd last col]

(3, 5, 4, 7, 5)

In [93]:
#single row or col
b[1,:] , b[:,0]

(array([5, 6]), array([2, 5, 3]))

In [142]:
import numpy as np
l=np.array([[8,9,10,11,12,13],[2,3,4,5,6,7], [12,13,141,15,161,17]])
l

array([[  8,   9,  10,  11,  12,  13],
       [  2,   3,   4,   5,   6,   7],
       [ 12,  13, 141,  15, 161,  17]])

In [105]:
l[1, 0:4:2] #l[row no, startIndex:endIndex(not included):stepSize]

array([2, 4])

In [107]:
l[1, 1:6:2] #6 works thought there are 6indices which means last index is 5

array([3, 5, 7])

In [109]:
#changing elements
b[0,1]=10
b

array([[ 2, 10],
       [ 5,  6],
       [ 3,  7]])

In [111]:
#changing all entire 1st column
l[:,1]=7
l

array([[  8,   7,  10,  11,  12,  13],
       [  2,   7,   4,   5,   6,   7],
       [ 12,   7, 141,  15, 161,  17]])

In [117]:
#3D array
z=np.array([[[0,1],[1,1]] #layer 0 made of 2d array(kind of like x axis)
            ,[[0,1],[1,1]]] #layer 1 made of 2d array(y axis))
z #(graph of f(x,y))

array([[[0, 1],
        [1, 1]],

       [[0, 1],
        [1, 1]]])

In [126]:
#to access elements
print(z[0,1,1]) #0th layer's 1st array's 1st element

1


In [127]:
z[0,1,1]=5
z

array([[[0, 1],
        [1, 5]],

       [[0, 1],
        [1, 1]]])

In [129]:
z1= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[0,0,0],[0,0,0],[0,0,0]]])
z1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [131]:
d4= np.array([
    [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[0,0,0],[0,0,0],[0,0,0]]
    ],
    [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[0,0,0],[0,0,0],[0,0,0]]
    ],
    [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[0,0,0],[0,0,0],[0,0,0]]
    ]
            ])
d4

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [141]:
q1=np.ones((5,5),dtype=int)
q1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [148]:
i=1
while (i<4):
    q1[i, 1:4:1]=0
    i+=1
q1
q1[2,2]=9
print(q1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [160]:
#method 2:
a1= np.ones((5,5),dtype=int)
z1= np.zeros((3,3),dtype=int)
z1[1,1]=9
print(a1," \n",z1)
a1[1:-1, 1:-1]=z1 #accessing [1st row till last row, 1st column till last column]
print(a1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]  
 [[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [172]:
a1=a.copy()
a1[0]=5
print(a1,a)
a1=a
a1[0]=5
print(a1, a)
 #a1 changed as well because a1=a is just a1 pointing at a and not a copy of a


[5. 3.] [2. 3.]
[5. 3.] [5. 3.]


In [209]:
#to repeat an array:
b[0,1]=4
print(f"this is b: \n{b}\n")
print(np.repeat(b,1))
b1=np.repeat(b,1)
print(np.repeat(b,2))
print(np.repeat(b,2,axis=0))
print(f"{np.repeat(b,2,axis=1)}\n")

#to reshape an array
print(f"{(np.repeat(b,2,axis=0)).reshape(3,4)}\n")

#stacking
#vertical
print(np.vstack([b1,b1]))
#horizontal
print(np.hstack([b1,b1]))

this is b: 
[[2 4]
 [5 6]
 [3 7]]

[2 4 5 6 3 7]
[2 2 4 4 5 5 6 6 3 3 7 7]
[[2 4]
 [2 4]
 [5 6]
 [5 6]
 [3 7]
 [3 7]]
[[2 2 4 4]
 [5 5 6 6]
 [3 3 7 7]]

[[2 4 2 4]
 [5 6 5 6]
 [3 7 3 7]]

[[2 4 5 6 3 7]
 [2 4 5 6 3 7]]
[2 4 5 6 3 7 2 4 5 6 3 7]


In [ ]:
#get data as array from a file
file=np.genfromtxt("/path",delimiter=" ") #default=float
file= file.astype('int32') #to convert to int


In [ ]:
#boolean masking
ba1= file > 50 #gives array of boolean, returns true in places of data where data is>50
ba2= np.any(file>50, axis=0) #returns array of boolean with condition checked in axis 0
print(b1 + "\n" + b2 + \"n")

In [ ]:
#adv indexing:
file[file>50] #givesan array of INDICES of data where data>50


In [217]:
#making list with index:
a2= np.array([9,1,2,3,4,5,6,7])
a3=a2[[0,1,5]] #a3 is a list of elements at indices [0,1,5] of a2
a3

array([9, 1, 5])

In [216]:
a4=a2[[-2]]
a4

array([6])

In [225]:
print(l)
a3= l[[0,1,2],[2,3,4]]
print(q3)
q4= l[0:3:2, 4:6:1]
print(q4)
#(using indexing): 
a4=l[[0,2],4:] #4: means 4 onwards 
print(a4)

[[  8   9  10  11  12  13]
 [  2   3   4   5   6   7]
 [ 12  13 141  15 161  17]]
[ 10   5 161]
[[ 12  13]
 [161  17]]
[[ 12  13]
 [161  17]]
